#define GEM_Z_OFFSET 0.0625f
#define CHECKPOINT_Z_OFFSET 0.01f

#define NUM_MAX_LIGHT_TYPES 5
#define NUM_MAX_LAMPS 1
#define NUM_MAX_PLATFORMS 15
#define NUM_MAX_GEMS 12
#define NUM_MAX_CHECKPOINTS 3
#define NUM_MAX_UPWINDS 1
#define NUM_MAX_TEXTBOXES 3

#define SKY_SCALE 1000.0f

#define AMBIENT_LIGHT_R 0.25f
#define AMBIENT_LIGHT_G 0.25f
#define AMBIENT_LIGHT_B 0.25f
#define AMBIENT_LIGHT_A 1.000f

#define PLAYER_RADIUS_Z 0.125f

#define PLAYER_CONTOUR_Z_RANGE 0.01f

#define TEXTBOX_ALPHA 0.5
#define TEXTBOX_FADE_OFF_RANGE 0.04
#define TEXTBOX_FADE_OFF_RANGE_CHECK 0.05
#define TEXTBOX_FADE_OFF_RANGE_INV 25